project_name: 'cowin-tracker'

builds:
  - main: ''
    goos: ['linux', 'darwin', 'windows']
    goarch: ['386', 'amd64']
    env:
      - CGO_ENABLED=0

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', 'demo', '^test:', 'Merge pull request', 'Merge branch']

archives:
  - format_overrides:
      - goos: 'windows'
        format: 'zip'
    wrap_in_directory: true
    files:
      - README.md